apiVersion: v1
kind: Service
metadata:
  name: that-agent-buildkit
spec:
  selector:
    app.kubernetes.io/name: that-agent
    app.kubernetes.io/component: buildkit
  ports:
    - name: buildkit
      port: 1234
      targetPort: 1234
