apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: that-agent-cluster
subjects:
  - kind: ServiceAccount
    name: that-agent
    # namespace is patched by kustomize overlay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: that-agent-cluster
