apiVersion: v1
kind: Service
metadata:
  name: that-agent-git-server
spec:
  selector:
    app.kubernetes.io/name: that-agent
    app.kubernetes.io/component: git-server
  ports:
    - name: git-http
      port: 9418
      targetPort: 9418
