//! Bootstrap command for creating the agent tools configuration.
//!
//! Creates `~/.that-agent/tools.toml` with a named profile that sets
//! appropriate policy levels for different use cases.

use super::{PolicyConfig, PolicyLevel, ThatToolsConfig, ToolPolicies};
use serde::Serialize;
use std::path::Path;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum InitError {
    #[error("configuration already exists at {0} — use --force to overwrite")]
    AlreadyExists(String),
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("serialization error: {0}")]
    Serialize(String),
}

#[derive(Debug, Serialize)]
pub struct InitResult {
    pub profile: String,
    pub config_path: String,
    pub created: bool,
}

/// Build a `ThatToolsConfig` with policy settings for the given profile name.
///
/// Recognized profiles:
/// - `safe` — conservative defaults, most write/exec operations require approval
/// - `agent` — allows execution and writes, still prompts for destructive operations
/// - `unrestricted` — all operations allowed without prompting
///
/// Unknown profile names fall back to `safe`.
pub fn config_for_profile(name: &str) -> ThatToolsConfig {
    let policy = match name {
        "agent" => PolicyConfig {
            default: PolicyLevel::Prompt,
            tools: ToolPolicies {
                code_read: PolicyLevel::Allow,
                code_edit: PolicyLevel::Allow,
                fs_read: PolicyLevel::Allow,
                fs_write: PolicyLevel::Allow,
                fs_delete: PolicyLevel::Prompt,
                shell_exec: PolicyLevel::Allow,
                search: PolicyLevel::Allow,
                memory: PolicyLevel::Allow,
                mem_compact: PolicyLevel::Allow,
                git_commit: PolicyLevel::Allow,
                git_push: PolicyLevel::Deny,
            },
        },
        "unrestricted" => PolicyConfig {
            default: PolicyLevel::Allow,
            tools: ToolPolicies {
                code_read: PolicyLevel::Allow,
                code_edit: PolicyLevel::Allow,
                fs_read: PolicyLevel::Allow,
                fs_write: PolicyLevel::Allow,
                fs_delete: PolicyLevel::Allow,
                shell_exec: PolicyLevel::Allow,
                search: PolicyLevel::Allow,
                memory: PolicyLevel::Allow,
                mem_compact: PolicyLevel::Allow,
                git_commit: PolicyLevel::Allow,
                git_push: PolicyLevel::Allow,
            },
        },
        // "safe" and any unknown profile
        _ => PolicyConfig {
            default: PolicyLevel::Prompt,
            tools: ToolPolicies {
                code_read: PolicyLevel::Allow,
                code_edit: PolicyLevel::Prompt,
                fs_read: PolicyLevel::Allow,
                fs_write: PolicyLevel::Prompt,
                fs_delete: PolicyLevel::Deny,
                shell_exec: PolicyLevel::Deny,
                search: PolicyLevel::Allow,
                memory: PolicyLevel::Allow,
                mem_compact: PolicyLevel::Allow,
                git_commit: PolicyLevel::Prompt,
                git_push: PolicyLevel::Deny,
            },
        },
    };

    ThatToolsConfig {
        policy,
        ..ThatToolsConfig::default()
    }
}

/// Create the agent tools configuration file at `~/.that-agent/tools.toml`.
///
/// Returns an error if the file already exists and `force` is false.
pub fn init(profile: &str, force: bool) -> Result<InitResult, InitError> {
    init_to(&super::agent_home_dir(), profile, force)
}

/// Write the tools configuration into `config_dir/tools.toml`.
///
/// Shared implementation used by `init` (agent home) and tests (temp dirs).
pub(crate) fn init_to(
    config_dir: &Path,
    profile: &str,
    force: bool,
) -> Result<InitResult, InitError> {
    let config_path = config_dir.join("tools.toml");

    if config_path.exists() && !force {
        return Err(InitError::AlreadyExists(
            config_path.to_string_lossy().to_string(),
        ));
    }

    // Create the directory if needed
    std::fs::create_dir_all(config_dir)?;

    let config = config_for_profile(profile);
    let toml_str =
        toml::to_string_pretty(&config).map_err(|e| InitError::Serialize(e.to_string()))?;

    let effective_profile = match profile {
        "agent" | "unrestricted" => profile,
        _ => "safe",
    };
    let content = format!(
        "# that-tools configuration — profile: {}\n# Generated by `that tools config-init`\n\n{}",
        effective_profile, toml_str
    );
    std::fs::write(&config_path, content)?;

    Ok(InitResult {
        profile: effective_profile.to_string(),
        config_path: config_path.to_string_lossy().to_string(),
        created: true,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_safe_profile_policy() {
        let config = config_for_profile("safe");
        assert_eq!(config.policy.tools.shell_exec, PolicyLevel::Deny);
        assert_eq!(config.policy.tools.fs_write, PolicyLevel::Prompt);
        assert_eq!(config.policy.tools.fs_delete, PolicyLevel::Deny);
        assert_eq!(config.policy.tools.code_edit, PolicyLevel::Prompt);
        assert_eq!(config.policy.tools.git_push, PolicyLevel::Deny);
    }

    #[test]
    fn test_agent_profile_policy() {
        let config = config_for_profile("agent");
        assert_eq!(config.policy.tools.shell_exec, PolicyLevel::Allow);
        assert_eq!(config.policy.tools.fs_write, PolicyLevel::Allow);
        assert_eq!(config.policy.tools.fs_delete, PolicyLevel::Prompt);
        assert_eq!(config.policy.tools.code_edit, PolicyLevel::Allow);
        assert_eq!(config.policy.tools.git_push, PolicyLevel::Deny);
    }

    #[test]
    fn test_unrestricted_profile_policy() {
        let config = config_for_profile("unrestricted");
        assert_eq!(config.policy.tools.shell_exec, PolicyLevel::Allow);
        assert_eq!(config.policy.tools.fs_write, PolicyLevel::Allow);
        assert_eq!(config.policy.tools.fs_delete, PolicyLevel::Allow);
        assert_eq!(config.policy.tools.code_edit, PolicyLevel::Allow);
        assert_eq!(config.policy.tools.git_push, PolicyLevel::Allow);
    }

    #[test]
    fn test_unknown_profile_falls_back_to_safe() {
        let config = config_for_profile("nonexistent");
        let safe = config_for_profile("safe");
        assert_eq!(config.policy, safe.policy);
    }

    #[test]
    fn test_init_creates_config_file() {
        let tmp = TempDir::new().unwrap();
        let result = init_to(tmp.path(), "agent", false).unwrap();
        assert!(result.created);
        assert_eq!(result.profile, "agent");

        let config_path = tmp.path().join("tools.toml");
        assert!(config_path.exists());

        // Verify it's valid TOML that deserializes to ThatToolsConfig
        let content = std::fs::read_to_string(&config_path).unwrap();
        let parsed: ThatToolsConfig = toml::from_str(&content).unwrap();
        assert_eq!(parsed.policy.tools.shell_exec, PolicyLevel::Allow);
    }

    #[test]
    fn test_init_refuses_overwrite_without_force() {
        let tmp = TempDir::new().unwrap();
        init_to(tmp.path(), "safe", false).unwrap();

        let err = init_to(tmp.path(), "agent", false).unwrap_err();
        assert!(matches!(err, InitError::AlreadyExists(_)));
    }

    #[test]
    fn test_init_allows_overwrite_with_force() {
        let tmp = TempDir::new().unwrap();
        init_to(tmp.path(), "agent", false).unwrap();

        let result = init_to(tmp.path(), "safe", true).unwrap();
        assert!(result.created);
        assert_eq!(result.profile, "safe");

        // Verify the file was overwritten with the new profile
        let config_path = tmp.path().join("tools.toml");
        let content = std::fs::read_to_string(&config_path).unwrap();
        let parsed: ThatToolsConfig = toml::from_str(&content).unwrap();
        assert_eq!(parsed.policy.tools.shell_exec, PolicyLevel::Deny);
    }

    #[test]
    fn test_serialization_roundtrip() {
        for profile in &["safe", "agent", "unrestricted"] {
            let config = config_for_profile(profile);
            let toml_str = toml::to_string_pretty(&config).unwrap();
            let parsed: ThatToolsConfig = toml::from_str(&toml_str).unwrap();
            assert_eq!(
                config.policy, parsed.policy,
                "roundtrip failed for {}",
                profile
            );
        }
    }
}
