apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "that-agent.serviceAccountName" . }}
  labels:
    {{- include "that-agent.labels" . | nindent 4 }}
automountServiceAccountToken: true
