apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: that-agent-default

resources:
  - ../../base
  - namespace.yaml
  - secret.yaml

images:
  - name: that-agent
    newName: ghcr.io/that-labs/that-agent
    newTag: latest

patches:
  - path: patch-configmap.yaml
