apiVersion: v1
kind: ConfigMap
metadata:
  name: that-agent-config
data:
  THAT_SANDBOX_K8S_NAMESPACE: "that-agent-default"
  THAT_SANDBOX_K8S_REGISTRY: "myregistry.localhost:5000"
  THAT_SANDBOX_K8S_REGISTRY_PUSH_ENDPOINT: "myregistry.localhost:5000"
  THAT_AGENT_NAME: "wolfy"
  THAT_AGENT_BOOTSTRAP_PROMPT: "It nevers enough"
  THAT_AGENT_PROVIDER: "openrouter"
  THAT_AGENT_MODEL: "anthropic/claude-sonnet-4.6"
  THAT_AGENT_MAX_TURNS: "150"