{{- if and .Values.buildkit.enabled (not .Values.buildkit.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "that-agent.fullname" . }}-buildkit
  labels:
    {{- include "that-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: buildkit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.buildkit.storage.size }}
  {{- if .Values.buildkit.storage.storageClassName }}
  storageClassName: {{ .Values.buildkit.storage.storageClassName | quote }}
  {{- end }}
{{- end }}
